### ISSUE TITLE
Unhandled exception (crash) in one of the last steps of cleansumstats pipeline

### ISSUE THREAD

**Issue by ofrei** [BioPsyk/cleansumstats#410]
I experienced a crash while running the pipeline, but I'm not sure which step crashed - I'm also copying execution trace
I'll check if this reproduces on another compute node that we have.
![image](https://github.com/BioPsyk/cleansumstats/assets/13171449/33b2e56a-9868-4cff-a0aa-aeffb85941bb)

![image](https://github.com/BioPsyk/cleansumstats/assets/13171449/01634673-50a3-47bd-a239-2661cf5b4f1e)

**Comment by ofrei** [comment]
Same commands work once I've submitted them to our HPC clusters via SLURM. The submit node where it crashed had 512 GB RAM and the same CPU architecture, so this was a bit strange, but nevermind - I'm closing this ticket, no need to investigate

**Comment by pappewaio** [comment]
@ofrei I have seen this before. I think it can happen when you use the same work and/or tmp folder when running multiple cleaning jobs. Since I started to set specific folders using -b and -w, I haven't seen it anymore.

-b <dir> 	 path to system tmp or scratch (default: /tmp)
-w <dir> 	 path to workdir/intermediate files (default: work)

**Comment by ofrei** [comment]
@pappewaio thanks, this makes sense - in the run that failed I've ran 3 jobs simultaneously using default's ``-b`` and ``-w``. In SLURM job I'm setting both to local scratch area which is unique for each job.
